# Generated by Django 4.2 on 2025-01-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_member_groups_alter_member_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('featured_image', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=200)),
                ('url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Usuario.project')),
                ('suggest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest', to='Usuario.project')),
            ],
        ),
    ]
