# Generated by Django 4.2 on 2025-01-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_project_project_suggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='Usuario.project')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_project', to='Usuario.skill')),
            ],
        ),
    ]
