# Generated by Django 4.2 on 2025-01-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
