# Generated by Django 4.2 on 2025-01-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_suscriptor_alter_post_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Usuario.post'),
        ),
        migrations.AddField(
            model_name='suggest',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='Usuario.project'),
        ),
        migrations.DeleteModel(
            name='Project_Suggest',
        ),
    ]
