# Generated by Django 4.2 on 2025-01-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_suggest_post_suggest_target_delete_project_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_skill',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project_skill',
            name='skill_project',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='post',
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(to='Usuario.skill'),
        ),
        migrations.AddField(
            model_name='post',
            name='suggests',
            field=models.ManyToManyField(to='Usuario.suggest'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='Usuario.skill'),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='Usuario.post'),
        ),
        migrations.DeleteModel(
            name='Member_Skill',
        ),
        migrations.DeleteModel(
            name='Project_Skill',
        ),
    ]
