# Generated by Django 4.2 on 2025-01-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_project_skill_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='suggests',
            field=models.ManyToManyField(blank=True, to='Usuario.post'),
        ),
    ]
