# Generated by Django 4.2 on 2025-01-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_alter_post_suggests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggest',
        ),
    ]
