# Generated by Django 5.1.5 on 2025-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_delete_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
