# Generated by Django 5.1.5 on 2025-01-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0015_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.CharField(blank=True, default='http://media.cubadebate.cu/wp-content/gallery/autores/oscar-figueredo-reinaldo.jpg', max_length=200, null=True),
        ),
    ]
